#[runner]
#fastReturns = false # apparently deprecated

[client]
showErrorDetails = false

[theme]
primaryColor = "#F63366"
backgroundColor = "black"
showSidebarNavigation = false 
# testing
#toolbarMode = "developer"
toolbarMode = "viewer"

[server]
headless = true
